{% set version = "0.5.4" %}

package:
  name: thermofun
  version: {{ version }}

source:
  url: https://github.com/thermomod/thermofun/archive/v{{ version }}.tar.gz
  sha256: 04e573beba46e838af4af3194e3427532dcd7a53b7f895c174e3e16afeb52bb8

  #git_url: https://dmiron@bitbucket.org/gems4/thermofun.git
  #git_rev: test-17

  #git_url: https://github.com/thermohub/thermofun.git
  #git_rev: gdmiron-patch-1

build:
  number: 0
#  skip: True  # [py2k or osx or c_compiler == 'toolchain_c']
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [win]
    - make   # [unix]
    - python  # [win or osx]
    - pip  # [win or osx]
    - setuptools  # [win or osx]
    - wheel  # [win or osx]

  host:
    - python
    - pip
    - setuptools
    - wheel
    - pybind11
    - chemicalfun >=0.1.13
    - spdlog
    - nlohmann_json >=3.7.0

  run:
    - python
    - chemicalfun >=0.1.13
    - spdlog
    - nlohmann_json >=3.7.0

test:
  imports:
    - thermofun

about:
  home: https://thermohub.org/thermofun/thermofun/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Standalone library for calculating temperature and pressure corrections of thermodynamic data for substances and reactions.
  doc_url: https://thermohub.org/thermofun/thermofun/
  dev_url: https://github.com/thermomod/thermofun

extra:
  recipe-maintainers:
    - gdmiron
    - allanleal
    - sdmytrievs
